#cloud-config

package_update: true
package_upgrade: true
packages:
  - openjdk-17-jre-headless
  - screen

runcmd:
  - wget 'https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar' -O minecraft_server.jar
  - echo "eula=true" > eula.txt
  - screen -dmS minecraft java -Xms1024M -Xmx1024M -jar minecraft_server.jar nogui
